### PR TITLE
feat: Shorten outputs (removing this_)

### PR DESCRIPTION
**Pull request by antonbabenko**
- feat: Shorten outputs (removing this_)
- feat: Shorten outputs (removing this_)

### CODE REVIEW

**Comment by antonbabenko** [comment]
[v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-route53/releases/v2.0.0) has been just released.

**Comment by koshkin-ccna** [comment]
Hi @antonbabenko,
thank you very much for maintaining all those great modules!

Are you going to remove 'this_' in all modules in this project in future?
If so, how would you advice to proceed with upgrade of already existing project which use current 'this' naming convention?

----
Еще раз спасибо за твою работу над этим проектом!

**Comment by antonbabenko** [comment]
Hi Michal,

Yes, we are going to remove `this_` in all modules during the next few days (hopefully) or when time allows.

All of these renames happen in a new major releases of each module so you should be able to just change the version of the module and update references in your code. When you run `terraform init && terraform apply` it will ask if you want to update the outputs which is usually rather safe operation.

Пож-та :)

**Comment by koshkin-ccna** [comment]
Gotcha, thanks for the prompt response! I am using terragrunt wrapper, but yeah, for new resources I'd just use a new tag release reference for the module.

**Pull request merged**
