### PR TITLE
feat: Allow specifying known values for the keys used to index the recordsets

### PR DESCRIPTION
**Pull request by flora-five**
## Description
Add an optional variable, `record_names`, to the records module, of type `list(string)`. If the list is not empty, then its values are used as keys of the `local.recordsets` map instead of the keys created by the module from possibly unknown yet values.

## Motivation and Context
The change is a possible solution to issue #59. By allowing the user of the records module to control the map keys, the user can also use the module when the value of name, type of set_identifier depends on resources that have to be created.

## Breaking Changes
There should be no breaking change. The users not affected by the issue can still use `var.records` as before.

## How Has This Been Tested?
- [X] I have tested and validated these changes using one or more of the provided `examples/*` projects

The complete example can be deployed completely with this change.

### CODE REVIEW

**Comment by antonbabenko** [comment]
Hi @flora-five !

Let's consider this approach as a workaround for issue #59 but I am not sure it is the most elegant though. One of my concerns is that I don't imagine people specifying valid values in `record_names` (e.g. `" A"` with space).

Instead of requiring users to provide a list of ids (`record_names`), can we do one of the following:
1. Change `records` to be `map(any)` or `any`, and the key will have to be always static (we use it in `for_each`)?
2. Can we add another property in `records` which we use as id with `for_each` instead of generating it?

What do you think?

**Comment by flora-five** [comment]
Hi!

> Let's consider this approach as a workaround for issue #59 but I am not sure it is the most elegant though. One of my concerns is that I don't imagine people specifying valid values in `record_names` (e.g. `" A"` with space).

Indeed, I agree with that. In the latest commit I have been able to reduce the cases requiring the caller to set the custom keys for the map. On the other hand, it would be nice for the caller to be able to specify custom keys when the keys generated by the module depend on values that are not known yet. Maybe the documentation could explain to the users the role of the internal map, how its keys are generated by the module and when does the caller need to specify custom keys.

> Instead of requiring users to provide a list of ids (`record_names`), can we do one of the following:
> 
> 1. Change `records` to be `map(any)` or `any`, and the key will have to be always static (we use it in `for_each`)?

If the type would be `map(any)`, then JSON encoding would not be needed for Terragrunt, but Terraform will not accept map items with different types (a record using `alias` vs a simple record) and the callers would have to handle the generation of the keys.

With the current type, `any`, the issue for plain Terraform users is the expression `try(jsondecode(var.records), var.records)`. It seems that because `var.records` is not fully known, the `jsondecode` or `try` call makes the entire result not known yet and Terraform cannot know the keys, even if they are actually static and fully known when the module is called.

To keep the type `any` for `var.records`, my idea is to use a separate variable, `records_json`, to receive the JSON encoded list from Terragrunt users. This way the creation of `local.records` does not depend on the content of `records` or `records_json` and, for Terraform users, Terraform can build the plan. It is a (minor, I think) breaking change for Terragrunt users.

> 2. Can we add another property in `records` which we use as id with `for_each` instead of generating it?

In the latest commit I've tried to do that, to use `map_key` if it exists in a record item. The code would try to use not-null values from `var.record_map_keys`, the attribute `map_key` if it exists in a record item or it will build the key itself.

> What do you think?

Maybe the most elegant way would be to not proceed with this work-around, set the type of `var.records` to `list(object({...})` and use the experimental support for optional object attributes to support all possible records. This way Terraform will know how to parse the environment variable set by Terragrunt.

Otherwise, to summarize this proposed work-around/fix:
- The issue is fixed for Terraform users. As an additional benefit, the Terraform users have `map_key` to override the internal map key if the internal map key depends on other values.
- Terragrunt users have to make a small change, to use `records_json` instead of `records`. If no record depends on unknown values, then this is the only change necessary. Otherwise they have to use `var.record_map_keys` to specify ALL the keys for the internal map. Maybe they can be helped a little more by having a submodule that takes as input the name, type and set_identifier of records, all statically specified, and returns as output the keys calculated as before. That output can be passed as input in `var.record_map_keys`.

What do you think?

**Comment by flora-five** [comment]
Just a note that the complete example still has the issue with Terraform 0.13.7.

**Comment by flora-five** [comment]
Hi!

@antonbabenko, when do you have time, what do you think about the changes so far? Should I continue by updating the docs?

Thank you!

**Comment by antonbabenko** [comment]
Thank you very much for this PR! It looks very solid and works.

I have spent another couple of hours during the weekend discovering&verifying edge cases, making some fine-tuning, and thinking about how to minimize compatibility breaks.

Please leave it like this for a week, I will push my updates as soon as I wrap things up and it should be ready to merge pretty soon.

**Pull request closed without merging**
